import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "CIT's Staff Hub",
  description: "Generated by create next app",
  icons: "/images/cit_normallogo.jpg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${dm_sans.className}  bg-white text-black w-full overflow-x-hidden`}>{children}</body>
    </html>
  );
}
